get:
  tags:
    - gateway
  summary: Get all routes
  parameters:
    - $ref: '../parameters.yaml#/namespace'
  responses:
    "200":
      description: Routes for gateway in the namespace
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '../objects.yaml#/route'