log:
  api: debug

server:
  listen: 0.0.0.0:8080
  # tls-cert: ../tests/certs/localhost.crt
  # tls-key: ../tests/certs/localhost.key
  assets: ../tests/certs/dist
  # cookie-secret: direktiv

oidc: 
  provider: dddd
  client-id: djhdsfjhdf
  secret: dhdhdh
  redirect: sdkskjksj
  # cookie-secret: sjksj
# backend:
#   url: http://127.0.0.1:9997
#   provider: https://jensgcompi.local/auth/realms/direktiv
#   secret: 8xHzO8i3hNMg-D3WSXEVpG9CfwBzqCmc
#   client-id: direktiv
# ui:
#   provider: https://jensgcompi.local/auth/realms/direktiv
#   logout: https://jensgcompi.local/auth/realms/direktiv/protocol/openid-connect/logout 
#   redirect: https://localhost:8080/callback
#   prefix: /ui
#   client-id: direktiv-ui
 