name: Run API e2e tests

on:
  push:
    paths-ignore:
      - ui/**
    branches:
      - main
  pull_request:
    paths-ignore:
      - ui/**

permissions:
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run end-to-end tests
        run: make docker-tests
