name: Run API e2e tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-section:
          - cli
          - engine
          - errors
          - events
          - filesystem
          - functions
          - gateway
          - logparser
          - mirror
          - namespace
          - registry
          - secrets
          - services
          - variables

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run end-to-end tests/${{ matrix.test-section }}
        run: TEST_SECTION=${{ matrix.test-section }} make docker-tests
