name: Lint backend code

on:
  push:
    paths-ignore:
      - ui/**
    tags:
      - v*
    branches:
      - main
  pull_request:
    paths-ignore:
      - ui/**

permissions:
  contents: read

jobs:
  golangci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55