name: 'Publish Storybook to Chromatic'

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0 # chromatic needs all commits
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}